import { ICrop } from "../interface/ICrop";
//https://csvjson.com/csv2json
const Crops: ICrop[] = [
  {
    "Object Id": "490",
    "Days in Stage 1 Growth": "1",
    "Days in Stage 2 Growth": "2",
    "Days in Stage 3 Growth": "3",
    "Days in Stage 4 Growth": "4",
    "Days in Stage 5 Growth": "3",
    "Growth Seasons": "fall",
    "Index In Sprite Sheet": "18",
    "Index Of Harvest": "276",
    "Regrow After Harvest": "-1",
    "Harvest Method": "0",
    "Chance For Extra Harvest": "false",
    "Min Extra Harvest": "",
    "Max Extra Harvest": "",
    "Max Harvest Increase Per Farming Level": "",
    "Chance For Extra Crops": "",
    "Raised Seeds": "false",
    "Tint Color": "false",
  },
  {
    "Object Id": "491",
    "Days in Stage 1 Growth": "1",
    "Days in Stage 2 Growth": "1",
    "Days in Stage 3 Growth": "1",
    "Days in Stage 4 Growth": "1",
    "Days in Stage 5 Growth": "",
    "Growth Seasons": "fall",
    "Index In Sprite Sheet": "19",
    "Index Of Harvest": "278",
    "Regrow After Harvest": "-1",
    "Harvest Method": "0",
    "Chance For Extra Harvest": "false",
    "Min Extra Harvest": "",
    "Max Extra Harvest": "",
    "Max Harvest Increase Per Farming Level": "",
    "Chance For Extra Crops": "",
    "Raised Seeds": "false",
    "Tint Color": "false",
  },
  {
    "Object Id": "492",
    "Days in Stage 1 Growth": "1",
    "Days in Stage 2 Growth": "3",
    "Days in Stage 3 Growth": "3",
    "Days in Stage 4 Growth": "3",
    "Days in Stage 5 Growth": "",
    "Growth Seasons": "fall",
    "Index In Sprite Sheet": "20",
    "Index Of Harvest": "280",
    "Regrow After Harvest": "-1",
    "Harvest Method": "0",
    "Chance For Extra Harvest": "false",
    "Min Extra Harvest": "",
    "Max Extra Harvest": "",
    "Max Harvest Increase Per Farming Level": "",
    "Chance For Extra Crops": "",
    "Raised Seeds": "false",
    "Tint Color": "false",
  },
  {
    "Object Id": "273",
    "Days in Stage 1 Growth": "1",
    "Days in Stage 2 Growth": "2",
    "Days in Stage 3 Growth": "2",
    "Days in Stage 4 Growth": "3",
    "Days in Stage 5 Growth": "",
    "Growth Seasons": "spring",
    "Index In Sprite Sheet": "34",
    "Index Of Harvest": "271",
    "Regrow After Harvest": "-1",
    "Harvest Method": "1",
    "Chance For Extra Harvest": "true",
    "Min Extra Harvest": "1",
    "Max Extra Harvest": "1",
    "Max Harvest Increase Per Farming Level": "10",
    "Chance For Extra Crops": ".1",
    "Raised Seeds": "false",
    "Tint Color": "false",
  },
  {
    "Object Id": "493",
    "Days in Stage 1 Growth": "1",
    "Days in Stage 2 Growth": "2",
    "Days in Stage 3 Growth": "1",
    "Days in Stage 4 Growth": "1",
    "Days in Stage 5 Growth": "2",
    "Growth Seasons": "fall",
    "Index In Sprite Sheet": "21",
    "Index Of Harvest": "282",
    "Regrow After Harvest": "5",
    "Harvest Method": "0",
    "Chance For Extra Harvest": "true",
    "Min Extra Harvest": "2",
    "Max Extra Harvest": "2",
    "Max Harvest Increase Per Farming Level": "0",
    "Chance For Extra Crops": ".1",
    "Raised Seeds": "false",
    "Tint Color": "false",
  },
  {
    "Object Id": "472",
    "Days in Stage 1 Growth": "1",
    "Days in Stage 2 Growth": "1",
    "Days in Stage 3 Growth": "1",
    "Days in Stage 4 Growth": "1",
    "Days in Stage 5 Growth": "",
    "Growth Seasons": "spring",
    "Index In Sprite Sheet": "0",
    "Index Of Harvest": "24",
    "Regrow After Harvest": "-1",
    "Harvest Method": "0",
    "Chance For Extra Harvest": "false",
    "Min Extra Harvest": "",
    "Max Extra Harvest": "",
    "Max Harvest Increase Per Farming Level": "",
    "Chance For Extra Crops": "",
    "Raised Seeds": "false",
    "Tint Color": "false",
  },
  {
    "Object Id": "494",
    "Days in Stage 1 Growth": "1",
    "Days in Stage 2 Growth": "1",
    "Days in Stage 3 Growth": "2",
    "Days in Stage 4 Growth": "2",
    "Days in Stage 5 Growth": "",
    "Growth Seasons": "fall",
    "Index In Sprite Sheet": "22",
    "Index Of Harvest": "284",
    "Regrow After Harvest": "-1",
    "Harvest Method": "0",
    "Chance For Extra Harvest": "false",
    "Min Extra Harvest": "",
    "Max Extra Harvest": "",
    "Max Harvest Increase Per Farming Level": "",
    "Chance For Extra Crops": "",
    "Raised Seeds": "false",
    "Tint Color": "false",
  },
  {
    "Object Id": "890",
    "Days in Stage 1 Growth": "1",
    "Days in Stage 2 Growth": "1",
    "Days in Stage 3 Growth": "1",
    "Days in Stage 4 Growth": "1",
    "Days in Stage 5 Growth": "",
    "Growth Seasons": "spring summer fall winter",
    "Index In Sprite Sheet": "47",
    "Index Of Harvest": "889",
    "Regrow After Harvest": "-1",
    "Harvest Method": "0",
    "Chance For Extra Harvest": "false",
    "Min Extra Harvest": "",
    "Max Extra Harvest": "",
    "Max Harvest Increase Per Farming Level": "",
    "Chance For Extra Crops": "",
    "Raised Seeds": "false",
    "Tint Color": "false",
  },
  {
    "Object Id": "473",
    "Days in Stage 1 Growth": "1",
    "Days in Stage 2 Growth": "1",
    "Days in Stage 3 Growth": "1",
    "Days in Stage 4 Growth": "3",
    "Days in Stage 5 Growth": "4",
    "Growth Seasons": "spring",
    "Index In Sprite Sheet": "1",
    "Index Of Harvest": "188",
    "Regrow After Harvest": "3",
    "Harvest Method": "0",
    "Chance For Extra Harvest": "false",
    "Min Extra Harvest": "",
    "Max Extra Harvest": "",
    "Max Harvest Increase Per Farming Level": "",
    "Chance For Extra Crops": "",
    "Raised Seeds": "true",
    "Tint Color": "false",
  },
  {
    "Object Id": "495",
    "Days in Stage 1 Growth": "3",
    "Days in Stage 2 Growth": "4",
    "Days in Stage 3 Growth": "",
    "Days in Stage 4 Growth": "",
    "Days in Stage 5 Growth": "",
    "Growth Seasons": "spring",
    "Index In Sprite Sheet": "23",
    "Index Of Harvest": "16",
    "Regrow After Harvest": "-1",
    "Harvest Method": "0",
    "Chance For Extra Harvest": "false",
    "Min Extra Harvest": "",
    "Max Extra Harvest": "",
    "Max Harvest Increase Per Farming Level": "",
    "Chance For Extra Crops": "",
    "Raised Seeds": "false",
    "Tint Color": "false",
  },
  {
    "Object Id": "474",
    "Days in Stage 1 Growth": "1",
    "Days in Stage 2 Growth": "2",
    "Days in Stage 3 Growth": "4",
    "Days in Stage 4 Growth": "4",
    "Days in Stage 5 Growth": "1",
    "Growth Seasons": "spring",
    "Index In Sprite Sheet": "2",
    "Index Of Harvest": "190",
    "Regrow After Harvest": "-1",
    "Harvest Method": "0",
    "Chance For Extra Harvest": "false",
    "Min Extra Harvest": "",
    "Max Extra Harvest": "",
    "Max Harvest Increase Per Farming Level": "",
    "Chance For Extra Crops": "",
    "Raised Seeds": "false",
    "Tint Color": "false",
  },
  {
    "Object Id": "496",
    "Days in Stage 1 Growth": "3",
    "Days in Stage 2 Growth": "4",
    "Days in Stage 3 Growth": "",
    "Days in Stage 4 Growth": "",
    "Days in Stage 5 Growth": "",
    "Growth Seasons": "summer",
    "Index In Sprite Sheet": "23",
    "Index Of Harvest": "396",
    "Regrow After Harvest": "-1",
    "Harvest Method": "0",
    "Chance For Extra Harvest": "false",
    "Min Extra Harvest": "",
    "Max Extra Harvest": "",
    "Max Harvest Increase Per Farming Level": "",
    "Chance For Extra Crops": "",
    "Raised Seeds": "false",
    "Tint Color": "false",
  },
  {
    "Object Id": "299",
    "Days in Stage 1 Growth": "1",
    "Days in Stage 2 Growth": "2",
    "Days in Stage 3 Growth": "2",
    "Days in Stage 4 Growth": "2",
    "Days in Stage 5 Growth": "",
    "Growth Seasons": "fall",
    "Index In Sprite Sheet": "39",
    "Index Of Harvest": "300",
    "Regrow After Harvest": "-1",
    "Harvest Method": "1",
    "Chance For Extra Harvest": "false",
    "Min Extra Harvest": "",
    "Max Extra Harvest": "",
    "Max Harvest Increase Per Farming Level": "",
    "Chance For Extra Crops": "",
    "Raised Seeds": "false",
    "Tint Color": "false",
  },
  {
    "Object Id": "431",
    "Days in Stage 1 Growth": "1",
    "Days in Stage 2 Growth": "2",
    "Days in Stage 3 Growth": "3",
    "Days in Stage 4 Growth": "2",
    "Days in Stage 5 Growth": "",
    "Growth Seasons": "summer fall",
    "Index In Sprite Sheet": "30",
    "Index Of Harvest": "421",
    "Regrow After Harvest": "-1",
    "Harvest Method": "0",
    "Chance For Extra Harvest": "false",
    "Min Extra Harvest": "",
    "Max Extra Harvest": "",
    "Max Harvest Increase Per Farming Level": "",
    "Chance For Extra Crops": "",
    "Raised Seeds": "false",
    "Tint Color": "false",
  },
  {
    "Object Id": "453",
    "Days in Stage 1 Growth": "1",
    "Days in Stage 2 Growth": "2",
    "Days in Stage 3 Growth": "2",
    "Days in Stage 4 Growth": "2",
    "Days in Stage 5 Growth": "",
    "Growth Seasons": "summer",
    "Index In Sprite Sheet": "28",
    "Index Of Harvest": "376",
    "Regrow After Harvest": "-1",
    "Harvest Method": "0",
    "Chance For Extra Harvest": "false",
    "Min Extra Harvest": "",
    "Max Extra Harvest": "",
    "Max Harvest Increase Per Farming Level": "",
    "Chance For Extra Crops": "",
    "Raised Seeds": "false",
    "Tint Color": "true 255 0 0 254 254 254 255 170 0",
  },
  {
    "Object Id": "475",
    "Days in Stage 1 Growth": "1",
    "Days in Stage 2 Growth": "1",
    "Days in Stage 3 Growth": "1",
    "Days in Stage 4 Growth": "2",
    "Days in Stage 5 Growth": "1",
    "Growth Seasons": "spring",
    "Index In Sprite Sheet": "3",
    "Index Of Harvest": "192",
    "Regrow After Harvest": "-1",
    "Harvest Method": "0",
    "Chance For Extra Harvest": "true",
    "Min Extra Harvest": "1",
    "Max Extra Harvest": "1",
    "Max Harvest Increase Per Farming Level": "0",
    "Chance For Extra Crops": ".2",
    "Raised Seeds": "false",
    "Tint Color": "false",
  },
  {
    "Object Id": "497",
    "Days in Stage 1 Growth": "3",
    "Days in Stage 2 Growth": "4",
    "Days in Stage 3 Growth": "",
    "Days in Stage 4 Growth": "",
    "Days in Stage 5 Growth": "",
    "Growth Seasons": "fall",
    "Index In Sprite Sheet": "23",
    "Index Of Harvest": "404",
    "Regrow After Harvest": "-1",
    "Harvest Method": "0",
    "Chance For Extra Harvest": "false",
    "Min Extra Harvest": "",
    "Max Extra Harvest": "",
    "Max Harvest Increase Per Farming Level": "",
    "Chance For Extra Crops": "",
    "Raised Seeds": "false",
    "Tint Color": "false",
  },
  {
    "Object Id": "476",
    "Days in Stage 1 Growth": "1",
    "Days in Stage 2 Growth": "1",
    "Days in Stage 3 Growth": "1",
    "Days in Stage 4 Growth": "1",
    "Days in Stage 5 Growth": "",
    "Growth Seasons": "spring",
    "Index In Sprite Sheet": "4",
    "Index Of Harvest": "248",
    "Regrow After Harvest": "-1",
    "Harvest Method": "0",
    "Chance For Extra Harvest": "false",
    "Min Extra Harvest": "",
    "Max Extra Harvest": "",
    "Max Harvest Increase Per Farming Level": "",
    "Chance For Extra Crops": "",
    "Raised Seeds": "false",
    "Tint Color": "false",
  },
  {
    "Object Id": "498",
    "Days in Stage 1 Growth": "3",
    "Days in Stage 2 Growth": "4",
    "Days in Stage 3 Growth": "",
    "Days in Stage 4 Growth": "",
    "Days in Stage 5 Growth": "",
    "Growth Seasons": "winter",
    "Index In Sprite Sheet": "23",
    "Index Of Harvest": "412",
    "Regrow After Harvest": "-1",
    "Harvest Method": "0",
    "Chance For Extra Harvest": "false",
    "Min Extra Harvest": "",
    "Max Extra Harvest": "",
    "Max Harvest Increase Per Farming Level": "",
    "Chance For Extra Crops": "",
    "Raised Seeds": "false",
    "Tint Color": "false",
  },
  {
    "Object Id": "433",
    "Days in Stage 1 Growth": "1",
    "Days in Stage 2 Growth": "2",
    "Days in Stage 3 Growth": "2",
    "Days in Stage 4 Growth": "3",
    "Days in Stage 5 Growth": "2",
    "Growth Seasons": "spring summer",
    "Index In Sprite Sheet": "40",
    "Index Of Harvest": "433",
    "Regrow After Harvest": "2",
    "Harvest Method": "0",
    "Chance For Extra Harvest": "true",
    "Min Extra Harvest": "4",
    "Max Extra Harvest": "4",
    "Max Harvest Increase Per Farming Level": "0",
    "Chance For Extra Crops": ".02",
    "Raised Seeds": "false",
    "Tint Color": "false",
  },
  {
    "Object Id": "455",
    "Days in Stage 1 Growth": "1",
    "Days in Stage 2 Growth": "2",
    "Days in Stage 3 Growth": "3",
    "Days in Stage 4 Growth": "2",
    "Days in Stage 5 Growth": "",
    "Growth Seasons": "summer",
    "Index In Sprite Sheet": "29",
    "Index Of Harvest": "593",
    "Regrow After Harvest": "-1",
    "Harvest Method": "0",
    "Chance For Extra Harvest": "false",
    "Min Extra Harvest": "",
    "Max Extra Harvest": "",
    "Max Harvest Increase Per Farming Level": "",
    "Chance For Extra Crops": "",
    "Raised Seeds": "false",
    "Tint Color":
      "true 0 208 255 99 255 210 255 212 0 255 144 122 255 0 238 206 91 255",
  },
  {
    "Object Id": "477",
    "Days in Stage 1 Growth": "1",
    "Days in Stage 2 Growth": "2",
    "Days in Stage 3 Growth": "2",
    "Days in Stage 4 Growth": "1",
    "Days in Stage 5 Growth": "",
    "Growth Seasons": "spring",
    "Index In Sprite Sheet": "5",
    "Index Of Harvest": "250",
    "Regrow After Harvest": "-1",
    "Harvest Method": "1",
    "Chance For Extra Harvest": "false",
    "Min Extra Harvest": "",
    "Max Extra Harvest": "",
    "Max Harvest Increase Per Farming Level": "",
    "Chance For Extra Crops": "",
    "Raised Seeds": "false",
    "Tint Color": "false",
  },
  {
    "Object Id": "499",
    "Days in Stage 1 Growth": "2",
    "Days in Stage 2 Growth": "7",
    "Days in Stage 3 Growth": "7",
    "Days in Stage 4 Growth": "7",
    "Days in Stage 5 Growth": "5",
    "Growth Seasons": "spring summer fall",
    "Index In Sprite Sheet": "24",
    "Index Of Harvest": "454",
    "Regrow After Harvest": "7",
    "Harvest Method": "0",
    "Chance For Extra Harvest": "false",
    "Min Extra Harvest": "",
    "Max Extra Harvest": "",
    "Max Harvest Increase Per Farming Level": "",
    "Chance For Extra Crops": "",
    "Raised Seeds": "false",
    "Tint Color": "false",
  },
  {
    "Object Id": "478",
    "Days in Stage 1 Growth": "2",
    "Days in Stage 2 Growth": "2",
    "Days in Stage 3 Growth": "2",
    "Days in Stage 4 Growth": "3",
    "Days in Stage 5 Growth": "4",
    "Growth Seasons": "spring",
    "Index In Sprite Sheet": "6",
    "Index Of Harvest": "252",
    "Regrow After Harvest": "-1",
    "Harvest Method": "0",
    "Chance For Extra Harvest": "false",
    "Min Extra Harvest": "",
    "Max Extra Harvest": "",
    "Max Harvest Increase Per Farming Level": "",
    "Chance For Extra Crops": "",
    "Raised Seeds": "false",
    "Tint Color": "false",
  },
  {
    "Object Id": "479",
    "Days in Stage 1 Growth": "1",
    "Days in Stage 2 Growth": "2",
    "Days in Stage 3 Growth": "3",
    "Days in Stage 4 Growth": "3",
    "Days in Stage 5 Growth": "3",
    "Growth Seasons": "summer",
    "Index In Sprite Sheet": "7",
    "Index Of Harvest": "254",
    "Regrow After Harvest": "-1",
    "Harvest Method": "0",
    "Chance For Extra Harvest": "false",
    "Min Extra Harvest": "",
    "Max Extra Harvest": "",
    "Max Harvest Increase Per Farming Level": "",
    "Chance For Extra Crops": "",
    "Raised Seeds": "false",
    "Tint Color": "false",
  },
  {
    "Object Id": "831",
    "Days in Stage 1 Growth": "1",
    "Days in Stage 2 Growth": "2",
    "Days in Stage 3 Growth": "3",
    "Days in Stage 4 Growth": "4",
    "Days in Stage 5 Growth": "",
    "Growth Seasons": "summer",
    "Index In Sprite Sheet": "42",
    "Index Of Harvest": "830",
    "Regrow After Harvest": "-1",
    "Harvest Method": "0",
    "Chance For Extra Harvest": "false",
    "Min Extra Harvest": "",
    "Max Extra Harvest": "",
    "Max Harvest Increase Per Farming Level": "",
    "Chance For Extra Crops": "",
    "Raised Seeds": "false",
    "Tint Color": "false",
  },
  {
    "Object Id": "833",
    "Days in Stage 1 Growth": "1",
    "Days in Stage 2 Growth": "3",
    "Days in Stage 3 Growth": "3",
    "Days in Stage 4 Growth": "4",
    "Days in Stage 5 Growth": "3",
    "Growth Seasons": "summer",
    "Index In Sprite Sheet": "43",
    "Index Of Harvest": "832",
    "Regrow After Harvest": "7",
    "Harvest Method": "0",
    "Chance For Extra Harvest": "false",
    "Min Extra Harvest": "",
    "Max Extra Harvest": "",
    "Max Harvest Increase Per Farming Level": "",
    "Chance For Extra Crops": "",
    "Raised Seeds": "false",
    "Tint Color": "false",
  },
  {
    "Object Id": "480",
    "Days in Stage 1 Growth": "2",
    "Days in Stage 2 Growth": "2",
    "Days in Stage 3 Growth": "2",
    "Days in Stage 4 Growth": "2",
    "Days in Stage 5 Growth": "3",
    "Growth Seasons": "summer",
    "Index In Sprite Sheet": "8",
    "Index Of Harvest": "256",
    "Regrow After Harvest": "4",
    "Harvest Method": "0",
    "Chance For Extra Harvest": "true",
    "Min Extra Harvest": "1",
    "Max Extra Harvest": "1",
    "Max Harvest Increase Per Farming Level": "0",
    "Chance For Extra Crops": ".05",
    "Raised Seeds": "false",
    "Tint Color": "false",
  },
  {
    "Object Id": "481",
    "Days in Stage 1 Growth": "1",
    "Days in Stage 2 Growth": "3",
    "Days in Stage 3 Growth": "3",
    "Days in Stage 4 Growth": "4",
    "Days in Stage 5 Growth": "2",
    "Growth Seasons": "summer",
    "Index In Sprite Sheet": "9",
    "Index Of Harvest": "258",
    "Regrow After Harvest": "4",
    "Harvest Method": "0",
    "Chance For Extra Harvest": "true",
    "Min Extra Harvest": "3",
    "Max Extra Harvest": "3",
    "Max Harvest Increase Per Farming Level": "0",
    "Chance For Extra Crops": ".02",
    "Raised Seeds": "false",
    "Tint Color": "false",
  },
  {
    "Object Id": "482",
    "Days in Stage 1 Growth": "1",
    "Days in Stage 2 Growth": "1",
    "Days in Stage 3 Growth": "1",
    "Days in Stage 4 Growth": "1",
    "Days in Stage 5 Growth": "1",
    "Growth Seasons": "summer",
    "Index In Sprite Sheet": "10",
    "Index Of Harvest": "260",
    "Regrow After Harvest": "3",
    "Harvest Method": "0",
    "Chance For Extra Harvest": "true",
    "Min Extra Harvest": "1",
    "Max Extra Harvest": "1",
    "Max Harvest Increase Per Farming Level": "0",
    "Chance For Extra Crops": ".03",
    "Raised Seeds": "false",
    "Tint Color": "false",
  },
  {
    "Object Id": "483",
    "Days in Stage 1 Growth": "1",
    "Days in Stage 2 Growth": "1",
    "Days in Stage 3 Growth": "1",
    "Days in Stage 4 Growth": "1",
    "Days in Stage 5 Growth": "",
    "Growth Seasons": "summer fall",
    "Index In Sprite Sheet": "11",
    "Index Of Harvest": "262",
    "Regrow After Harvest": "-1",
    "Harvest Method": "1",
    "Chance For Extra Harvest": "false",
    "Min Extra Harvest": "",
    "Max Extra Harvest": "",
    "Max Harvest Increase Per Farming Level": "",
    "Chance For Extra Crops": "",
    "Raised Seeds": "false",
    "Tint Color": "false",
  },
  {
    "Object Id": "484",
    "Days in Stage 1 Growth": "2",
    "Days in Stage 2 Growth": "1",
    "Days in Stage 3 Growth": "2",
    "Days in Stage 4 Growth": "1",
    "Days in Stage 5 Growth": "",
    "Growth Seasons": "summer",
    "Index In Sprite Sheet": "12",
    "Index Of Harvest": "264",
    "Regrow After Harvest": "-1",
    "Harvest Method": "0",
    "Chance For Extra Harvest": "false",
    "Min Extra Harvest": "",
    "Max Extra Harvest": "",
    "Max Harvest Increase Per Farming Level": "",
    "Chance For Extra Crops": "",
    "Raised Seeds": "false",
    "Tint Color": "false",
  },
  {
    "Object Id": "485",
    "Days in Stage 1 Growth": "2",
    "Days in Stage 2 Growth": "1",
    "Days in Stage 3 Growth": "2",
    "Days in Stage 4 Growth": "2",
    "Days in Stage 5 Growth": "2",
    "Growth Seasons": "summer",
    "Index In Sprite Sheet": "13",
    "Index Of Harvest": "266",
    "Regrow After Harvest": "-1",
    "Harvest Method": "0",
    "Chance For Extra Harvest": "false",
    "Min Extra Harvest": "",
    "Max Extra Harvest": "",
    "Max Harvest Increase Per Farming Level": "",
    "Chance For Extra Crops": "",
    "Raised Seeds": "false",
    "Tint Color": "false",
  },
  {
    "Object Id": "486",
    "Days in Stage 1 Growth": "2",
    "Days in Stage 2 Growth": "3",
    "Days in Stage 3 Growth": "2",
    "Days in Stage 4 Growth": "3",
    "Days in Stage 5 Growth": "3",
    "Growth Seasons": "summer",
    "Index In Sprite Sheet": "14",
    "Index Of Harvest": "268",
    "Regrow After Harvest": "-1",
    "Harvest Method": "0",
    "Chance For Extra Harvest": "false",
    "Min Extra Harvest": "",
    "Max Extra Harvest": "",
    "Max Harvest Increase Per Farming Level": "",
    "Chance For Extra Crops": "",
    "Raised Seeds": "false",
    "Tint Color": "false",
  },
  {
    "Object Id": "487",
    "Days in Stage 1 Growth": "2",
    "Days in Stage 2 Growth": "3",
    "Days in Stage 3 Growth": "3",
    "Days in Stage 4 Growth": "3",
    "Days in Stage 5 Growth": "3",
    "Growth Seasons": "summer fall",
    "Index In Sprite Sheet": "15",
    "Index Of Harvest": "270",
    "Regrow After Harvest": "4",
    "Harvest Method": "0",
    "Chance For Extra Harvest": "false",
    "Min Extra Harvest": "",
    "Max Extra Harvest": "",
    "Max Harvest Increase Per Farming Level": "",
    "Chance For Extra Crops": "",
    "Raised Seeds": "false",
    "Tint Color": "false",
  },
  {
    "Object Id": "301",
    "Days in Stage 1 Growth": "1",
    "Days in Stage 2 Growth": "1",
    "Days in Stage 3 Growth": "2",
    "Days in Stage 4 Growth": "3",
    "Days in Stage 5 Growth": "3",
    "Growth Seasons": "fall",
    "Index In Sprite Sheet": "38",
    "Index Of Harvest": "398",
    "Regrow After Harvest": "3",
    "Harvest Method": "0",
    "Chance For Extra Harvest": "false",
    "Min Extra Harvest": "",
    "Max Extra Harvest": "",
    "Max Harvest Increase Per Farming Level": "",
    "Chance For Extra Crops": "",
    "Raised Seeds": "true",
    "Tint Color": "false",
  },
  {
    "Object Id": "488",
    "Days in Stage 1 Growth": "1",
    "Days in Stage 2 Growth": "1",
    "Days in Stage 3 Growth": "1",
    "Days in Stage 4 Growth": "1",
    "Days in Stage 5 Growth": "1",
    "Growth Seasons": "fall",
    "Index In Sprite Sheet": "16",
    "Index Of Harvest": "272",
    "Regrow After Harvest": "5",
    "Harvest Method": "0",
    "Chance For Extra Harvest": "true",
    "Min Extra Harvest": "1",
    "Max Extra Harvest": "1",
    "Max Harvest Increase Per Farming Level": "0",
    "Chance For Extra Crops": ".002",
    "Raised Seeds": "false",
    "Tint Color": "false",
  },
  {
    "Object Id": "302",
    "Days in Stage 1 Growth": "1",
    "Days in Stage 2 Growth": "1",
    "Days in Stage 3 Growth": "2",
    "Days in Stage 4 Growth": "3",
    "Days in Stage 5 Growth": "4",
    "Growth Seasons": "summer",
    "Index In Sprite Sheet": "37",
    "Index Of Harvest": "304",
    "Regrow After Harvest": "1",
    "Harvest Method": "0",
    "Chance For Extra Harvest": "false",
    "Min Extra Harvest": "",
    "Max Extra Harvest": "",
    "Max Harvest Increase Per Farming Level": "",
    "Chance For Extra Crops": "",
    "Raised Seeds": "true",
    "Tint Color": "false",
  },
  {
    "Object Id": "489",
    "Days in Stage 1 Growth": "2",
    "Days in Stage 2 Growth": "2",
    "Days in Stage 3 Growth": "1",
    "Days in Stage 4 Growth": "2",
    "Days in Stage 5 Growth": "1",
    "Growth Seasons": "fall",
    "Index In Sprite Sheet": "17",
    "Index Of Harvest": "274",
    "Regrow After Harvest": "-1",
    "Harvest Method": "0",
    "Chance For Extra Harvest": "false",
    "Min Extra Harvest": "",
    "Max Extra Harvest": "",
    "Max Harvest Increase Per Farming Level": "",
    "Chance For Extra Crops": "",
    "Raised Seeds": "false",
    "Tint Color": "false",
  },
  {
    "Object Id": "885",
    "Days in Stage 1 Growth": "1",
    "Days in Stage 2 Growth": "2",
    "Days in Stage 3 Growth": "2",
    "Days in Stage 4 Growth": "2",
    "Days in Stage 5 Growth": "",
    "Growth Seasons": "spring summer fall winter",
    "Index In Sprite Sheet": "44",
    "Index Of Harvest": "771",
    "Regrow After Harvest": "-1",
    "Harvest Method": "1",
    "Chance For Extra Harvest": "true",
    "Min Extra Harvest": "4",
    "Max Extra Harvest": "7",
    "Max Harvest Increase Per Farming Level": "0",
    "Chance For Extra Crops": ".01",
    "Raised Seeds": "false",
    "Tint Color": "false",
  },
  {
    "Object Id": "347",
    "Days in Stage 1 Growth": "2",
    "Days in Stage 2 Growth": "4",
    "Days in Stage 3 Growth": "6",
    "Days in Stage 4 Growth": "6",
    "Days in Stage 5 Growth": "6",
    "Growth Seasons": "fall",
    "Index In Sprite Sheet": "32",
    "Index Of Harvest": "417",
    "Regrow After Harvest": "-1",
    "Harvest Method": "0",
    "Chance For Extra Harvest": "false",
    "Min Extra Harvest": "",
    "Max Extra Harvest": "",
    "Max Harvest Increase Per Farming Level": "",
    "Chance For Extra Crops": "",
    "Raised Seeds": "false",
    "Tint Color": "false",
  },
  {
    "Object Id": "425",
    "Days in Stage 1 Growth": "1",
    "Days in Stage 2 Growth": "4",
    "Days in Stage 3 Growth": "4",
    "Days in Stage 4 Growth": "3",
    "Days in Stage 5 Growth": "",
    "Growth Seasons": "fall",
    "Index In Sprite Sheet": "31",
    "Index Of Harvest": "595",
    "Regrow After Harvest": "-1",
    "Harvest Method": "0",
    "Chance For Extra Harvest": "false",
    "Min Extra Harvest": "",
    "Max Extra Harvest": "",
    "Max Harvest Increase Per Farming Level": "",
    "Chance For Extra Crops": "",
    "Raised Seeds": "false",
    "Tint Color":
      "true 187 0 255 119 137 255 71 227 255 255 127 144 205 178 255 140 119 255",
  },
  {
    "Object Id": "745",
    "Days in Stage 1 Growth": "1",
    "Days in Stage 2 Growth": "1",
    "Days in Stage 3 Growth": "2",
    "Days in Stage 4 Growth": "2",
    "Days in Stage 5 Growth": "2",
    "Growth Seasons": "spring",
    "Index In Sprite Sheet": "36",
    "Index Of Harvest": "400",
    "Regrow After Harvest": "4",
    "Harvest Method": "0",
    "Chance For Extra Harvest": "true",
    "Min Extra Harvest": "1",
    "Max Extra Harvest": "1",
    "Max Harvest Increase Per Farming Level": "0",
    "Chance For Extra Crops": ".02",
    "Raised Seeds": "false",
    "Tint Color": "false",
  },
  {
    "Object Id": "427",
    "Days in Stage 1 Growth": "1",
    "Days in Stage 2 Growth": "1",
    "Days in Stage 3 Growth": "2",
    "Days in Stage 4 Growth": "2",
    "Days in Stage 5 Growth": "",
    "Growth Seasons": "spring",
    "Index In Sprite Sheet": "26",
    "Index Of Harvest": "591",
    "Regrow After Harvest": "-1",
    "Harvest Method": "0",
    "Chance For Extra Harvest": "false",
    "Min Extra Harvest": "",
    "Max Extra Harvest": "",
    "Max Harvest Increase Per Farming Level": "",
    "Chance For Extra Crops": "",
    "Raised Seeds": "false",
    "Tint Color": "true 255 186 255 223 191 255 255 246 0 255 80 0 255 158 193",
  },
  {
    "Object Id": "802",
    "Days in Stage 1 Growth": "2",
    "Days in Stage 2 Growth": "2",
    "Days in Stage 3 Growth": "2",
    "Days in Stage 4 Growth": "3",
    "Days in Stage 5 Growth": "3",
    "Growth Seasons": "spring summer fall winter",
    "Index In Sprite Sheet": "41",
    "Index Of Harvest": "90",
    "Regrow After Harvest": "3",
    "Harvest Method": "0",
    "Chance For Extra Harvest": "false",
    "Min Extra Harvest": "",
    "Max Extra Harvest": "",
    "Max Harvest Increase Per Farming Level": "",
    "Chance For Extra Crops": "",
    "Raised Seeds": "false",
    "Tint Color": "false",
  },
  {
    "Object Id": "429",
    "Days in Stage 1 Growth": "1",
    "Days in Stage 2 Growth": "2",
    "Days in Stage 3 Growth": "2",
    "Days in Stage 4 Growth": "2",
    "Days in Stage 5 Growth": "",
    "Growth Seasons": "spring",
    "Index In Sprite Sheet": "27",
    "Index Of Harvest": "597",
    "Regrow After Harvest": "-1",
    "Harvest Method": "0",
    "Chance For Extra Harvest": "false",
    "Min Extra Harvest": "",
    "Max Extra Harvest": "",
    "Max Harvest Increase Per Farming Level": "",
    "Chance For Extra Crops": "",
    "Raised Seeds": "false",
    "Tint Color":
      "true 35 127 255 109 131 255 112 207 255 191 228 255 94 121 255 40 150 255",
  },
];
export default Crops;
